### PR TITLE
Updated text on the homepage but will touch up on css

### PR DESCRIPTION
**Pull request by CalebGeb1209**
I need to touch up on the css but changed up the text slogans

### CODE REVIEW

**Review by ygebre1 — COMMENTED** [review]
The text looks good, as it really fits the structure of the project structure.

**Review by ArmaanAnchala — COMMENTED** [review]
This looks good. The text will help the users have a better understanding of the product.

**Review by EBOSAVAGE — COMMENTED** [review]
I have reviewed your code and I like the structure of it. It is concise and increases readability.

**Review by NikNemani — APPROVED** [review]
Change looks fine to me and align more with our accessibility goal, you should be good to merge it.

**Pull request merged**
