### PR TITLE
Changed code to display Nissan Leaf on Home Page

### PR DESCRIPTION
**Pull request by ArmaanAnchala**
Changed the code to display a Nissan Leaf image instead of a Tesla. Learned from client that he wanted to display cars that are more affordable and thus made the change.

### CODE REVIEW

**Review by CalebGeb1209 — COMMENTED** [review]
Looks good. The image is more realistic for our clientele.

**Review by ygebre1 — COMMENTED** [review]
The image fit better for the overrall target demographic of this project.

**Review by NikNemani — CHANGES_REQUESTED** [review]
Image looks fine, but you need to change the css so that the image can fill the screen to the bottom like the previous tesla image. Alternatively you can place a horizontal rule tag below the image and our little info blurb, and then place something else below it to up that empty space. Please make these changes, and then you can merge this to main

**Review by NikNemani — APPROVED** [review]
Looks fine for now. We will definitely have to change this though, the UI still looks a little wonky but it does incorporate the user feedback we got so it is a step in the right direction. Go ahead and merge it

**Pull request merged**
