### PR TITLE
Added Price Filter and Random Car Prices

### PR DESCRIPTION
**Pull request by EBOSAVAGE**
Basically the title. Added random car prices and filtration of cars based on car prices.

### CODE REVIEW

**Review by CalebGeb1209 — COMMENTED** [review]
Added price filter and random car prices. Functionalities updated as described. Nice Work

**Review by ArmaanAnchala — COMMENTED** [review]
This looks good. Just make sure to adjust your code if there are any merge conflicts.

**Review by EBOSAVAGE — COMMENTED** [review]
I have reviewed the changes after attempting to resolve the merge conflict and I believe that the code is working, but more concise. I would recommend running locally as part of review just to make sure that it works for everyone.

**Review by justin910113 — COMMENTED** [review]
contains certain merge conflicts as this is implemented but not submitted in previous sprint. Make sure to resolve these conflicts make them compatible with sprint 3 implementation otherwise functionality looks good

**Pull request closed without merging**
