### PR TITLE
Added a responsive layout to the home page

### PR DESCRIPTION
**Pull request by ygebre1**
Modified the css files to make the files more responsive and to make it look good on all devices

### CODE REVIEW

**Review by ArmaanAnchala — COMMENTED** [review]
This looks good. This will make our homepage look better on all types of platforms such as mobile devices.

**Review by CalebGeb1209 — COMMENTED** [review]
The responsive layout looks clean and pleasant to look at. Nice Job with how to aligned the margins.

**Review by NikNemani — CHANGES_REQUESTED** [review]
Overall pretty good, the only issue is I think the image should come first then the text should come after. It just looks a little strange especially since the text doesn't have any styling. Make this change and then it should be good to be merged. Good Job!

**Review by NikNemani — APPROVED** [review]
Good job, these changes look good. You can merge it now

**Pull request merged**
